In [1]:
import numpy as np

# 1. Array Creation

#### Create a 1D array of numbers from 10 to 50.

In [8]:
arr1 = np.arange(10,51)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create a 3x3 array of random numbers between 0 and 1.

In [9]:
rand_arr = np.random.random((3,3))
rand_arr

array([[0.17428789, 0.24391051, 0.03004712],
       [0.19367191, 0.69005563, 0.96187617],
       [0.13529739, 0.13707529, 0.09469545]])

# 2. Array Attributes

#### Find the shape, size, and data type of the array you created in the previous task

In [13]:
print(rand_arr.shape)
print(rand_arr.size)
print(rand_arr.dtype)

(3, 3)
9
float64


# 3. Basic Operations

#### Add 5 to every element of a 1D array.

In [14]:
arr1+5

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

#### Multiply two 2D arrays element-wise

In [15]:
arr1*2

array([ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38,  40,  42,  44,
        46,  48,  50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,
        72,  74,  76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,
        98, 100])

# 4. Indexing and Slicing

#### Create a 5x5 array of integers from 1 to 25.

In [22]:
arr2 = np.arange(1,26)
arr2 = arr2.reshape((5,5))
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### The first row.

In [23]:
arr2[0]

array([1, 2, 3, 4, 5])

#### The last column.

In [24]:
arr2[:,-1:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

#### A subarray of the first three rows and first two columns

In [25]:
arr2[:3,:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

# 5. Aggregation

#### Create a 10-element array of random integers between 1 and 100.

In [32]:
arr3 = np.random.random(10)*100//1
arr3

array([38., 34., 29., 34., 59., 49., 38., 57., 67., 57.])

#### The maximum value.

In [34]:
arr3.max()

67.0

#### The minimum value.

In [35]:
arr3.min()

29.0

#### The mean and standard deviation.

In [37]:
arr3.mean(),arr3.std()

(46.2, 12.512393855693642)

# 6. Reshaping

#### Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix

In [39]:
np.arange(1,13).reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 7. Broadcasting

#### Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row

In [44]:
np.ones((3,3))+np.arange(1,4)

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

# 8. Filtering

#### Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.

In [47]:
arr4 = np.random.random(10)*50//1
arr4[arr4%5==0]

array([35., 45.])

# 9. Matrix Multiplication 

#### Create two 2x2 matrices and perform matrix multiplication.

In [48]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,3],[2,1]])
np.dot(a,b)

array([[ 8,  5],
       [20, 13]])

# 10. Advanced Indexing

#### Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [50]:
mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
np.diag(mat)

array([ 1,  6, 11, 16])